{% set version = "0.2.4" %}

package:
  name: cykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cykdtree/cykdtree-{{ version }}.tar.gz
  sha256: e58104def3f030dc9bd73e4b9a1575cedafec78354d3d37fa455f3478a3200f2
  patches:
    - no_test_import.patch

build:
  number: 1007
  skip: True  # [osx or win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython <3
    - mpi4py
    - numpy
  run:
    - python
    - mpi4py
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cykdtree
  commands:

about:
  home: https://langmm@bitbucket.org/langmm/cykdtree
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Cython based KD-Tree'

extra:
  recipe-maintainers:
    - ocefpaf
