travis:
  secure:
    BINSTAR_TOKEN: VFUNwgnYp58YuUKwdb8a9DDpfxG8y9GvYMAJA+J1E1iqIE893fju4yHq3Jfu/wdvxiEhEXNjl/zpLojtgjTA2QVt6nbYOuupj/hllamIhr32RqtTlKbtYnmeyK2xldSyR4MEDLltKBy/JB8XuPpAPTPOaeCmciw+bW2zmB8wOBZZPD1U/O+TYv11OzYDoWeibY4ukZKcbrOYAOfz4LlfElGAGcipAutWqYVhswXvlfJjvktg3w9T5K0ZAv0py5rMWkwnLz0AYgo2XzufZgj1hnwk5t7rpvsv9aU4t5rCkgAXO71FYf+j5ZcJ8qA2QS3mvJmKmm2dZwYOxAnR1iihqI5NNeutgqkMv4k2zm4O9gh42XPXaltiAZ4EA6dhmSQDER1ZQ//JY1c4M3l35TNi5SJ4q7fptFL4XQZIs/q0aFnW6CcaWRiTXlwPyia2c1CyF2DlDdLosFUb6Q3hqEkGD/6LY7ns5dvHaTCjGhTCMtploBYzAlYK6dS7hL+5VbVB1+IlxeJi+HwSukn58YG5/2YmOniUGID1QqQQcfwF6ySJHPHN+MrSeydIBUtjatSx5eoBwG1kKefXVO5O2ZeFOO/9GjkxvkTI+NnWjlQ574HJuAlij2NmqrrbC0FgJ8d6XLE4emZa7IQbJd3VJyL6+g3ODorZTr0szeEDPhd2o+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
