travis:
  secure:
    BINSTAR_TOKEN: UZwGPUdHmRBGSZhGzdWREp84lGbME7dlZko9zsQBUPsxBpHpYrFR3lVJwW2w/i7RwRZHgiAje9/L/Ui8W84B6vZhn5ksTa7Ej5uPczTF8HZJwcliO4pHgeHSWhrwqU6X7hyRKpUyCVS7PFdttUQZqX/i4fyl2BsDQrkG1HJFvPGtArC7AZdraa/N/qOixCAb/uTZdjmynJdzZBKNVYCLxAof8sqHVFHC/Tgy4HnI/dpYw5nRa7BRmfuA7u95z/HRYNmGELqAYc6rToHWYKkONi/fPzMJwe6rGo/hghVicLcIMtlorjuSDX54T/p9i4yC/xhrWHtn6JyZzHLKD0c4VfxnGM+mV6r5UO0xJXVM6RWdqpm/w1CMily+5TWdFG4/wDkPQ+0bAxo1iEh3RrRQjpB9xUZWalte7XyEqE7W5rKfqRjDcyq/xL6Ry05OHW0s8DpDMYNeoZShnB+lDSghr3TUrE85xKkShmHUw5zss6yLChFoRBYUu+gx9FK4s2I2lf69c7MCETb1C61SbY+R1gMwTsZaQuaFUpJU6ej+I1peJeU+2qdywuHI/8XRvvu5EkEDJ9Jvm3yTK89w4RSSdfRXqOynUcnSgBoFswwwnVY9bFHWub3jm2o59iMGITV5UDW6ebjbv4/s+nw/B3giN6g2fReX9yNBpyrep/q9eUU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
